IDIR = ../include ../libs/inih
CC=gcc
CFLAGS =$(foreach d, $(IDIR), -I$d)

ODIR=../obj
LDIR =../libs/inih/extra/
LFLAGS = $(foreach d, $(LDIR), -L$d)
BDIR = ../build

LIBS= -linih

DEPS = $(foreach d, $(IDIR), $(wildcard $d/*.h))

