IDIR = ../include ../libs/inih
CC=gcc
CFLAGS =$(foreach d, $(IDIR), -I$d)

ODIR=../obj
LDIR =../libs/
LFLAGS = $(foreach d, $(LDIR), -L$d)
BDIR = ../build

LIBS= -linih

DEPS = $(foreach d, $(IDIR), $(wildcard $d/*.h))

SRC = $(wildcard *.c)
HEAS = $(wildcard *.h)
_OBJ = $(SRC:.c=.o)
OBJ = $(patsubst %,$(ODIR)/$(APPNAME)/%,$(_OBJ))

$(ODIR)/$(APPNAME)/%.o: %.c $(DEPS) $(HEAS)
	$(CC) -c -o $@ $< $(CFLAGS) $(LFLAGS)

$(APPNAME) : $(OBJ)
	$(CC) -o $(BDIR)/$@ $^ $(CFLAGS) $(LFLAGS) $(LIBS)


